version: "3.8"

services:
  frontend:
    build: ./gwq-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./gwq-backend
    ports:
      - "5010:5010"
    env_file:
      - ./gwq-backend/.env
