version: "3.8"

services:
  frontend:
    build: 
      context: ./gwq-frontend
      args:
        REACT_APP_BACKEND_HOST: http://backend:5010
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_HOST=http://backend:5010
    depends_on:
      - backend

  backend:
    build: ./gwq-backend
    ports:
      - "5010:5010"
    env_file:
      - ./gwq-backend/.env
